name: better_http_flutter
description: "A better version of http but still use http for Flutter"
version: 0.0.1
homepage:

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
#  better_utils_flutter:
#    git:
#      url: https://github.com/Virakyuth-PK/better_utils_flutter.git
#      ref: 0.0.1  # branch name
  better_widget_flutter:
    git:
      url: https://github.com/Virakyuth-PK/better_widget_flutter.git
      ref: 0.0.1  # branch name
  flutter_image_compress: ^2.4.0
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter: